name: ServerBooster
version: ${version}
description: Advanced server performance optimizer - Entity limiter, optimizer, and item merger. Remastered for 1.21.x
authors: [SrCodex]
api-version: "1.17"
main: dev.srcodex.serverbooster.ServerBoosterPlugin
load: POSTWORLD
folia-supported: true

softdepend:
  - ProtocolLib

permissions:
  serverbooster.*:
    description: Access all commands
    default: op
    children:
      serverbooster.reload: true
      serverbooster.mobs.count: true
      serverbooster.mobs.limits: true
      serverbooster.mobs.check: true
      serverbooster.chunks.blockphysics: true
      serverbooster.optimize: true
  serverbooster.reload:
    description: Access to reload command
    default: op
  serverbooster.mobs.count:
    description: Access to count command
    default: op
  serverbooster.mobs.limits:
    description: Access to limits command
    default: op
  serverbooster.mobs.check:
    description: Access to check command
    default: op
  serverbooster.chunks.blockphysics:
    description: Access to blockphysics command
    default: op
  serverbooster.optimize:
    description: Access to optimize command
    default: op

commands:
  serverbooster:
    description: ServerBooster main command
    aliases: [sb, sbooster]
    usage: /<command> [reload|count|limits|check|optimize|blockphysics]
